# Generated by Django 4.0.5 on 2022-07-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='shinu', max_length=30)),
                ('email', models.EmailField(default='shinu@gmail.com', max_length=30)),
                ('password', models.CharField(default=12345, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='create_an_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('Mobile', models.PositiveIntegerField(default=1234567898)),
                ('address', models.CharField(max_length=200)),
                ('PIN', models.IntegerField(default=12345678)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('account_type', models.CharField(default='savings', max_length=20)),
                ('initial_balance', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=20)),
                ('Register', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.register')),
            ],
        ),
    ]
